version: '3'

services:
  ark-admin:
    image: arklnk/ark-admin-zero:latest
    container_name: ark-admin
    ports:
      - "7001:7001"
    restart: always
    networks:
      - ark_admin_net

networks:
  ark_admin_net:
    driver: bridge