// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
	Account    string `json:"account"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type InfoResp struct {
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type ProfileResp struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   int64  `json:"gender"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Remark   string `json:"remark"`
	Avatar   string `json:"avatar"`
}

type UpdateProfileReq struct {
	Username string `json:"username" validate:"required,min=2,max=12"`
	Nickname string `json:"nickname"`
	Gender   int64  `json:"gender" validate:"gte=0,lte=2"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Remark   string `json:"remark"`
	Avatar   string `json:"avatar"`
}

type Menu struct {
	Id           int64  `json:"id"`
	ParentId     int64  `json:"parentId"`
	Name         string `json:"name"`
	Router       string `json:"router"`
	Type         int64  `json:"type"`
	Icon         string `json:"icon"`
	OrderNum     int64  `json:"orderNum"`
	ViewPath     string `json:"viewPath"`
	IsShow       int64  `json:"isShow"`
	ActiveRouter string `json:"activeRouter"`
}

type PermMenuResp struct {
	Menus []Menu   `json:"menus"`
	Perms []string `json:"perms"`
}

type PasswordReq struct {
	OldPassword string `json:"oldPassword" validate:"min=6,max=12"`
	NewPassword string `json:"newPassword" validate:"min=6,max=12"`
}

type CaptchaResp struct {
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
}

type PermMenu struct {
	Id           int64    `json:"id"`
	ParentId     int64    `json:"parentId"`
	Name         string   `json:"name"`
	Router       string   `json:"router"`
	Perms        []string `json:"perms"`
	Type         int64    `json:"type"`
	Icon         string   `djsonb:"icon"`
	OrderNum     int64    `json:"order_num"`
	ViewPath     string   `json:"view_path"`
	IsShow       int64    `json:"is_show"`
	ActiveRouter string   `json:"active_router"`
}

type PermMenuListResp struct {
	PermMenuList []PermMenu `json:"permMenuList"`
}
