// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
	Account    string `json:"account"`
	Password   string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UserInfoResp struct {
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type UserProfileInfoResp struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Gender   uint64 `json:"gender"`
	Email    string `json:"email"`
	Mobile   string `json:"mobile"`
	Remark   string `json:"remark"`
	Avatar   string `json:"avatar"`
}

type UpdateProfileReq struct {
	Username string `json:"username"  validate:"required,min=2,max=12"`
	Nickname string `json:"nickname"  validate:"omitempty,min=2,max=12"`
	Gender   uint64 `json:"gender"    validate:"gte=0,lte=2"`
	Email    string `json:"email"     validate:"omitempty,email"`
	Mobile   string `json:"mobile"    validate:"omitempty,len=11"`
	Avatar   string `json:"avatar"    validate:"required,url"`
}

type Menu struct {
	Id           uint64 `json:"id"`
	ParentId     uint64 `json:"parentId"`
	Name         string `json:"name"`
	Router       string `json:"router"`
	Type         uint64 `json:"type"`
	Icon         string `json:"icon"`
	OrderNum     uint64 `json:"orderNum"`
	ViewPath     string `json:"viewPath"`
	IsShow       uint64 `json:"isShow"`
	ActiveRouter string `json:"activeRouter"`
}

type UserPermMenuResp struct {
	Menus []Menu   `json:"menus"`
	Perms []string `json:"perms"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"oldPassword"  validate:"min=6,max=12"`
	NewPassword string `json:"newPassword"  validate:"min=6,max=12"`
}

type LoginCaptchaResp struct {
	CaptchaId  string `json:"captchaId"`
	VerifyCode string `json:"verifyCode"`
}

type GenerateAvatarResp struct {
	AvatarUrl string `json:"avatarUrl"`
}

type PermMenu struct {
	Id           uint64   `json:"id"`
	ParentId     uint64   `json:"parentId"`
	Name         string   `json:"name"`
	Router       string   `json:"router"`
	Perms        []string `json:"perms"`
	Type         uint64   `json:"type"`
	Icon         string   `json:"icon"`
	OrderNum     uint64   `json:"orderNum"`
	ViewPath     string   `json:"viewPath"`
	IsShow       uint64   `json:"isShow"`
	ActiveRouter string   `json:"activeRouter"`
	Has          uint64   `json:"has"`
}

type SysPermMenuListResp struct {
	PermMenuList []PermMenu `json:"list"`
}

type AddSysPermMenuReq struct {
	ParentId     uint64   `json:"parentId"      validate:"number,gte=0"`
	Name         string   `json:"name"          validate:"min=2,max=50"`
	Router       string   `json:"router"        validate:"omitempty,max=1024"`
	Perms        []string `json:"perms"         validate:"omitempty,unique"`
	Type         uint64   `json:"type"          validate:"number,gte=0,lte=2"`
	Icon         string   `json:"icon"          validate:"omitempty,max=200"`
	OrderNum     uint64   `json:"orderNum"      validate:"number,gte=0,lte=9999"`
	ViewPath     string   `json:"viewPath"      validate:"omitempty,max=1024"`
	IsShow       uint64   `json:"isShow"        validate:"number,gte=0,lte=1"`
	ActiveRouter string   `json:"activeRouter"  validate:"omitempty,max=1024"`
}

type DeleteSysPermMenuReq struct {
	Id uint64 `json:"id"  validate:"number,gte=1"`
}

type UpdateSysPermMenuReq struct {
	Id           uint64   `json:"id"            validate:"number,gte=1"`
	ParentId     uint64   `json:"parentId"      validate:"number,gte=0"`
	Name         string   `json:"name"          validate:"min=2,max=50"`
	Router       string   `json:"router"        validate:"omitempty,max=1024"`
	Perms        []string `json:"perms"         validate:"omitempty,unique"`
	Type         uint64   `json:"type"          validate:"number,gte=0,lte=2"`
	Icon         string   `json:"icon"          validate:"omitempty,max=200"`
	OrderNum     uint64   `json:"orderNum"      validate:"number,gte=0,lte=9999"`
	ViewPath     string   `json:"viewPath"      validate:"omitempty,max=1024"`
	IsShow       uint64   `json:"isShow"        validate:"number,gte=0,lte=1"`
	ActiveRouter string   `json:"activeRouter"  validate:"omitempty,max=1024"`
}

type Role struct {
	Id          uint64   `json:"id"`
	ParentId    uint64   `json:"parentId"`
	Name        string   `json:"name"`
	UniqueKey   string   `json:"uniqueKey"`
	PermMenuIds []uint64 `json:"permMenuIds"`
	Remark      string   `json:"remark"`
	Status      uint64   `json:"status"`
	OrderNum    uint64   `json:"orderNum"`
}

type SysRoleListResp struct {
	RoleList []Role `json:"list"`
}

type AddSysRoleReq struct {
	ParentId    uint64   `json:"parentId"     validate:"number,gte=0"`
	Name        string   `json:"name"         validate:"min=2,max=50"`
	UniqueKey   string   `json:"uniqueKey"    validate:"min=2,max=50"`
	PermMenuIds []uint64 `json:"permMenuIds"  validate:"omitempty,unique"`
	Remark      string   `json:"remark"       validate:"max=200"`
	Status      uint64   `json:"status"       validate:"number,gte=0,lte=1"`
	OrderNum    uint64   `json:"orderNum"     validate:"number,gte=0,lte=9999"`
}

type DeleteSysRoleReq struct {
	Id uint64 `json:"id"  validate:"number,gte=2"`
}

type UpdateSysRoleReq struct {
	Id          uint64   `json:"id"           validate:"number,gte=1"`
	ParentId    uint64   `json:"parentId"     validate:"number,gte=0"`
	UniqueKey   string   `json:"uniqueKey"    validate:"min=2,max=50"`
	Name        string   `json:"name"         validate:"min=2,max=50"`
	PermMenuIds []uint64 `json:"permMenuIds"  validate:"omitempty,unique"`
	Remark      string   `json:"remark"       validate:"max=200"`
	Status      uint64   `json:"status"       validate:"number,gte=0,lte=1"`
	OrderNum    uint64   `json:"orderNum"     validate:"number,gte=0,lte=9999"`
}

type Dept struct {
	Id        uint64 `json:"id"`
	ParentId  uint64 `json:"parentId"`
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	UniqueKey string `json:"uniqueKey"`
	Type      uint64 `json:"type"`
	Status    uint64 `json:"status"`
	OrderNum  uint64 `json:"orderNum"`
	Remark    string `json:"remark"`
}

type SysDeptListResp struct {
	DeptList []Dept `json:"list"`
}

type AddSysDeptReq struct {
	ParentId  uint64 `json:"parentId"   validate:"number,gte=0"`
	Name      string `json:"name"       validate:"min=2,max=50"`
	FullName  string `json:"fullName"   validate:"omitempty,min=2,max=50"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"`
	Type      uint64 `json:"type"       validate:"number,gte=1,lte=3"`
	Status    uint64 `json:"status"     validate:"number,gte=0,lte=1"`
	OrderNum  uint64 `json:"orderNum"   validate:"number,gte=0,lte=9999"`
	Remark    string `json:"remark"     validate:"max=200"`
}

type DeleteSysDeptReq struct {
	Id uint64 `json:"id"  validate:"number,gte=1"`
}

type UpdateSysDeptReq struct {
	Id        uint64 `json:"id"         validate:"number,gte=1"`
	ParentId  uint64 `json:"parentId"   validate:"number,gte=0"`
	Name      string `json:"name"       validate:"min=2,max=50"`
	FullName  string `json:"fullName"   validate:"omitempty,min=2,max=50"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"`
	Type      uint64 `json:"type"       validate:"number,gte=1,lte=3"`
	Status    uint64 `json:"status"     validate:"number,gte=0,lte=1"`
	OrderNum  uint64 `json:"orderNum"   validate:"number,gte=0,lte=9999"`
	Remark    string `json:"remark"     validate:"max=200"`
}

type Job struct {
	Id       uint64 `json:"id"`
	Name     string `json:"name"`
	Status   uint64 `json:"status"`
	OrderNum uint64 `json:"orderNum"`
}

type SysJobPageReq struct {
	Page  uint64 `form:"page"   validate:"number,gte=1"`
	Limit uint64 `form:"limit"  validate:"number,gte=1"`
}

type SysJobPagePagination struct {
	Page  uint64 `json:"page"`
	Limit uint64 `json:"limit"`
	Total uint64 `json:"total"`
}

type SysJobPageResp struct {
	JobList    []Job                `json:"list"`
	Pagination SysJobPagePagination `json:"pagination"`
}

type AddSysJobReq struct {
	Name     string `json:"name"      validate:"min=2,max=50"`
	Status   uint64 `json:"status"    validate:"number,gte=0,lte=1"`
	OrderNum uint64 `json:"orderNum"  validate:"number,gte=0,lte=9999"`
}

type DeleteSysJobReq struct {
	Id uint64 `json:"id"  validate:"number,gte=1"`
}

type UpdateSysJobReq struct {
	Id       uint64 `json:"id"        validate:"number,gte=1"`
	Name     string `json:"name"      validate:"min=2,max=50"`
	Status   uint64 `json:"status"    validate:"number,gte=0,lte=1"`
	OrderNum uint64 `json:"orderNum"  validate:"number,gte=0,lte=9999"`
}

type Profession struct {
	Id       uint64 `json:"id"`
	Name     string `json:"name"`
	Status   uint64 `json:"status"`
	OrderNum uint64 `json:"orderNum"`
}

type SysProfessionPageReq struct {
	Page  uint64 `form:"page"   validate:"number,gte=1"`
	Limit uint64 `form:"limit"  validate:"number,gte=1"`
}

type ProfessionPagePagination struct {
	Page  uint64 `json:"page"`
	Limit uint64 `json:"limit"`
	Total uint64 `json:"total"`
}

type SysProfessionPageResp struct {
	ProfessionList []Profession             `json:"list"`
	Pagination     ProfessionPagePagination `json:"pagination"`
}

type AddSysProfessionReq struct {
	Name     string `json:"name"      validate:"min=2,max=50"`
	Status   uint64 `json:"status"    validate:"number,gte=0,lte=1"`
	OrderNum uint64 `json:"orderNum"  validate:"number,gte=0,lte=9999"`
}

type DeleteSysProfessionReq struct {
	Id uint64 `json:"id"  validate:"number,gte=1"`
}

type UpdateSysProfessionReq struct {
	Id       uint64 `json:"id"        validate:"number,gte=1"`
	Name     string `json:"name"      validate:"min=2,max=50"`
	Status   uint64 `json:"status"    validate:"number,gte=0,lte=1"`
	OrderNum uint64 `json:"orderNum"  validate:"number,gte=0,lte=9999"`
}

type UserProfession struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

type UserJob struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

type UserDept struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

type UserRole struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

type User struct {
	Id         uint64         `json:"id"`
	Account    string         `json:"account"`
	Username   string         `json:"username"`
	Nickname   string         `json:"nickname"`
	Gender     uint64         `json:"gender"`
	Email      string         `json:"email"`
	Mobile     string         `json:"mobile"`
	Profession UserProfession `json:"profession"`
	Job        UserJob        `json:"job"`
	Dept       UserDept       `json:"dept"`
	Roles      []UserRole     `json:"roles"`
	Status     uint64         `json:"status"`
	OrderNum   uint64         `json:"orderNum"`
	Remark     string         `json:"remark"`
}

type SysUserPageReq struct {
	Page   uint64 `form:"page"    validate:"number,gte=1"`
	Limit  uint64 `form:"limit"   validate:"number,gte=1"`
	DeptId uint64 `form:"deptId"  validate:"number,gte=0"`
}

type UserPagePagination struct {
	Page  uint64 `json:"page"`
	Limit uint64 `json:"limit"`
	Total uint64 `json:"total"`
}

type SysUserPageResp struct {
	UserList   []User             `json:"list"`
	Pagination UserPagePagination `json:"pagination"`
}

type AddSysUserReq struct {
	Account      string   `json:"account"       validate:"min=4,max=50"`
	Username     string   `json:"username"      validate:"min=2,max=50"`
	Nickname     string   `json:"nickname"      validate:"omitempty,min=2,max=50"`
	Gender       uint64   `json:"gender"        validate:"number,gte=0,lte=2"`
	Email        string   `json:"email"         validate:"omitempty,email"`
	Mobile       string   `json:"mobile"        validate:"omitempty,min=11"`
	ProfessionId uint64   `json:"professionId"  validate:"number,gte=1"`
	JobId        uint64   `json:"jobId"         validate:"number,gte=1"`
	DeptId       uint64   `json:"deptId"        validate:"number,gte=1"`
	RoleIds      []uint64 `json:"roleIds"       validate:"unique"`
	Status       uint64   `json:"status"        validate:"number,gte=0,lte=1"`
	OrderNum     uint64   `json:"orderNum"      validate:"number,gte=0,lte=9999"`
	Remark       string   `json:"remark"        validate:"max=200"`
}

type DeleteSysUserReq struct {
	Id uint64 `json:"id"  validate:"number,gte=2"`
}

type UpdateSysUserReq struct {
	Id           uint64   `json:"id"            validate:"number,gte=2"`
	Username     string   `json:"username"      validate:"min=2,max=50"`
	Nickname     string   `json:"nickname"      validate:"omitempty,min=2,max=50"`
	Gender       uint64   `json:"gender"        validate:"number,gte=0,lte=2"`
	Email        string   `json:"email"         validate:"omitempty,email"`
	Mobile       string   `json:"mobile"        validate:"omitempty,min=11"`
	ProfessionId uint64   `json:"professionId"  validate:"number,gte=1"`
	JobId        uint64   `json:"jobId"         validate:"number,gte=1"`
	DeptId       uint64   `json:"deptId"        validate:"number,gte=1"`
	RoleIds      []uint64 `json:"roleIds"       validate:"unique"`
	Status       uint64   `json:"status"        validate:"number,gte=0,lte=1"`
	OrderNum     uint64   `json:"orderNum"      validate:"number,gte=0,lte=9999"`
	Remark       string   `json:"remark"        validate:"max=200"`
}

type UpdateSysUserPasswordReq struct {
	Id       uint64 `json:"id"        validate:"number,gte=2"`
	Password string `json:"password"  validate:"min=6,max=12"`
}

type GetSysUserRdpjInfoReq struct {
	UserId uint64 `form:"userId"  validate:"number,gte=0"`
}

type Rdpj struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

type DeptTree struct {
	Id       uint64 `json:"id"`
	ParentId uint64 `json:"parentId"`
	Name     string `json:"name"`
}

type RoleTree struct {
	Id       uint64 `json:"id"`
	ParentId uint64 `json:"parentId"`
	Name     string `json:"name"`
	Has      uint64 `json:"has"`
}

type GetSysUserRdpjInfoResp struct {
	Role       []RoleTree `json:"role"`
	Dept       []DeptTree `json:"dept"`
	Profession []Rdpj     `json:"profession"`
	Job        []Rdpj     `json:"job"`
}

type ConfigDict struct {
	Id        uint64 `json:"id"`
	ParentId  uint64 `json:"parentId"`
	Name      string `json:"name"`
	Type      uint64 `json:"type"`
	UniqueKey string `json:"uniqueKey"`
	Value     string `json:"value"`
	OrderNum  uint64 `json:"orderNum"`
	Remark    string `json:"remark"`
	Status    uint64 `json:"status"`
}

type ConfigDictListResp struct {
	DictList []ConfigDict `json:"list"`
}

type ConfigDictPageReq struct {
	Page     uint64 `form:"page"      validate:"number,gte=1"`
	Limit    uint64 `form:"limit"     validate:"number,gte=1"`
	ParentId uint64 `form:"parentId"  validate:"number,gte=0"`
}

type ConfigDictPagination struct {
	Page  uint64 `json:"page"`
	Limit uint64 `json:"limit"`
	Total uint64 `json:"total"`
}

type ConfigDictPageResp struct {
	ConfigDictList []ConfigDict         `json:"list"`
	Pagination     ConfigDictPagination `json:"pagination"`
}

type AddConfigDictReq struct {
	ParentId  uint64 `json:"parentId"   validate:"number,gte=0"`
	Name      string `json:"name"       validate:"min=2,max=50"`
	Type      uint64 `json:"type"       validate:"number,gte=1,lte=12"`
	UniqueKey string `json:"uniqueKey"  validate:"min=2,max=50"`
	Value     string `json:"value"      validate:"max=2048"`
	OrderNum  uint64 `json:"orderNum"   validate:"gte=0,lte=9999"`
	Remark    string `json:"remark"     validate:"max=200"`
	Status    uint64 `json:"status"     validate:"number,gte=0,lte=1"`
}

type DeleteConfigDictReq struct {
	Id uint64 `json:"id"  validate:"number,gte=1"`
}

type UpdateConfigDictReq struct {
	Id       uint64 `json:"id"        validate:"number,gte=1"`
	ParentId uint64 `json:"parentId"  validate:"number,gte=0"`
	Name     string `json:"name"      validate:"min=2,max=50"`
	Type     uint64 `json:"type"      validate:"number,gte=1,lte=12"`
	Value    string `json:"value"     validate:"max=2048"`
	OrderNum uint64 `json:"orderNum"  validate:"gte=0,lte=9999"`
	Remark   string `json:"remark"    validate:"max=200"`
	Status   uint64 `json:"status"    validate:"number,gte=0,lte=1"`
}

type LogLogin struct {
	Id         uint64 `json:"id"`
	Account    string `json:"account"`
	Ip         string `json:"ip"`
	Uri        string `json:"uri"`
	Status     uint64 `json:"status"`
	CreateTime string `json:"createTime"`
}

type LogLoginPageReq struct {
	Page  uint64 `form:"page"   validate:"number,gte=1"`
	Limit uint64 `form:"limit"  validate:"number,gte=1"`
}

type LogLoginPagePagination struct {
	Page  uint64 `json:"page"`
	Limit uint64 `json:"limit"`
	Total uint64 `json:"total"`
}

type LogLoginPageResp struct {
	LogLoginList []LogLogin             `json:"list"`
	Pagination   LogLoginPagePagination `json:"pagination"`
}
