// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDeptFieldNames          = builder.RawFieldNames(&SysDept{})
	sysDeptRows                = strings.Join(sysDeptFieldNames, ",")
	sysDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	sysDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDeptFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheArkAdminSysDeptIdPrefix        = "cache:arkAdmin:sysDept:id:"
	cacheArkAdminSysDeptUniqueKeyPrefix = "cache:arkAdmin:sysDept:uniqueKey:"
)

type (
	sysDeptModel interface {
		Insert(ctx context.Context, data *SysDept) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SysDept, error)
		FindOneByUniqueKey(ctx context.Context, uniqueKey string) (*SysDept, error)
		Update(ctx context.Context, data *SysDept) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSysDeptModel struct {
		sqlc.CachedConn
		table string
	}

	SysDept struct {
		Id         uint64    `db:"id"`          // 编号
		ParentId   uint64    `db:"parent_id"`   // 父级id
		Name       string    `db:"name"`        // 部门简称
		FullName   string    `db:"full_name"`   // 部门全称
		UniqueKey  string    `db:"unique_key"`  // 唯一值
		Type       uint64    `db:"type"`        // 1=公司 2=子公司 3=部门
		Status     uint64    `db:"status"`      // 0=禁用 1=开启
		OrderNum   uint64    `db:"order_num"`   // 排序值
		Remark     string    `db:"remark"`      // 备注
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newSysDeptModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultSysDeptModel {
	return &defaultSysDeptModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`sys_dept`",
	}
}

func (m *defaultSysDeptModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	arkAdminSysDeptIdKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptIdPrefix, id)
	arkAdminSysDeptUniqueKeyKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptUniqueKeyPrefix, data.UniqueKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, arkAdminSysDeptIdKey, arkAdminSysDeptUniqueKeyKey)
	return err
}

func (m *defaultSysDeptModel) FindOne(ctx context.Context, id uint64) (*SysDept, error) {
	arkAdminSysDeptIdKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptIdPrefix, id)
	var resp SysDept
	err := m.QueryRowCtx(ctx, &resp, arkAdminSysDeptIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDeptRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDeptModel) FindOneByUniqueKey(ctx context.Context, uniqueKey string) (*SysDept, error) {
	arkAdminSysDeptUniqueKeyKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptUniqueKeyPrefix, uniqueKey)
	var resp SysDept
	err := m.QueryRowIndexCtx(ctx, &resp, arkAdminSysDeptUniqueKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `unique_key` = ? limit 1", sysDeptRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uniqueKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDeptModel) Insert(ctx context.Context, data *SysDept) (sql.Result, error) {
	arkAdminSysDeptIdKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptIdPrefix, data.Id)
	arkAdminSysDeptUniqueKeyKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptUniqueKeyPrefix, data.UniqueKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDeptRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ParentId, data.Name, data.FullName, data.UniqueKey, data.Type, data.Status, data.OrderNum, data.Remark)
	}, arkAdminSysDeptIdKey, arkAdminSysDeptUniqueKeyKey)
	return ret, err
}

func (m *defaultSysDeptModel) Update(ctx context.Context, newData *SysDept) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	arkAdminSysDeptIdKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptIdPrefix, data.Id)
	arkAdminSysDeptUniqueKeyKey := fmt.Sprintf("%s%v", cacheArkAdminSysDeptUniqueKeyPrefix, data.UniqueKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysDeptRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ParentId, newData.Name, newData.FullName, newData.UniqueKey, newData.Type, newData.Status, newData.OrderNum, newData.Remark, newData.Id)
	}, arkAdminSysDeptIdKey, arkAdminSysDeptUniqueKeyKey)
	return err
}

func (m *defaultSysDeptModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheArkAdminSysDeptIdPrefix, primary)
}

func (m *defaultSysDeptModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysDeptRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysDeptModel) tableName() string {
	return m.table
}
